name = "notcursesada"
description = "notcurses text user interface library binding"
version = "2.2.3"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
